spring:
  datasource:
    url: jdbc:h2:mem:myFirstH2Bd
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /myFirstH2Bd
      settings:
        trace: on
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
